### ISSUE TITLE
Confused naming with regular and solid

### ISSUE THREAD

**Issue by buddhaCode** [andreiio/blade-iconoir#61]
Hi,
thanks for your package.

I had some issues with the naming. I was searching for some "vegan" icons through https://blade-ui-kit.com/blade-icons. I found a neat icon in this package. The website states the name "vegan", but the icon component in Blade couldn't find the icon. As I was looking up the issue in the source code, I found out, that I need to call the icon with "regular-vegan".

That's a bit confusing as the Blade UI Icon and the Iconic website named the icon just "vegan". Unfortunately
, I couldn't find any hint in the Readme of this package about that particular naming scheme.

Also, there is an issue with the naming scheme for solid icons. On the Iconic website the "solid" term it suffixed to the name. As on your implementation it is prefixed. Besides, the solid icons are not listed on the Blade UI Icon website search.

Best, Arne

**Comment by andreiio** [comment]
Hi,

What shows up on blade-ui-kit.com is managed through their own repo. It looks like they updated the package versions for several icon packages [just yesterday](https://github.com/blade-ui-kit/blade-ui-kit.com/commit/aacd6ffa94c59b894a65c816ab996d25a7ecf463#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R14).

The naming scheme I used is a flattened version of iconoir's [existing directory structure](https://github.com/iconoir-icons/iconoir/tree/main/icons), and aims to solve a few issues:

1. it normalizes component names with other blade-icons packages, using a format like `<x-iconoir-solid-warning-triangle />` instead of `<x-iconoir-solid.warning-triangle />` (note the dot);
2. it prevents collisions between icons that share the same name across the two variants (like `check-circle`, for instance);
3. by not further altering the filenames, it keeps the update process simple.

While this might not be the best solution, I find its verbosity very useful. If you can write a clearer explanation than what's already in the readme, I'll gladly accept a pull request.

**Comment by buddhaCode** [comment]
Dear Andrei,
thank you for your reply. I can see your reasons. Unfortunately, I do not agree with all of them.

Regarding 1: I don't now much about other packages. So I can't compare how this normalizes the component names. I see the difference with the dot. But I don't understand their consequences.
Regarding 2: The [original naming convention](https://iconoir.com/docs/naming-convention##:~:text=Styles) already takes care of this. Regular icons don't have suffix/prefix, as the solid icons are prefixed with `-solid`. So there can never be any collisions.
Regarding 3: That's totally valid ;)

From my perspective, the developer should have a nice "on boarding" experience. Thus, I think one should follow the naming convention of the original package. All [other listed libraries](https://iconoir.com/docs/packages/iconoir-react) do this as well.

I opened a PR with a little addition to the Readme file. Maybe you are ok with this.

Best, Arne

**Comment by andreiio** [comment]
> From my perspective, the developer should have a nice "on boarding" experience. Thus, I think one should follow the naming convention of the original package.

I agree. I'll have a go at using the original naming convention.

**Comment by andreiio** [comment]
I think this PR solves the issue. Would appreciate it if you could have a look and let me know if I've missed something.

**Comment by buddhaCode** [comment]
Hi Andrei, that’s absolute fine for me. Thank you so much.
I have to apologize, if my tone was a bit rude or disrespectful. It’s your package and your idea. You can what ever you want. I just wanted to give my kindful opinion.

**Comment by andreiio** [comment]
> I have to apologize, if my tone was a bit rude or disrespectful
Not at all. I haven't given the file structure much thought until now, but I realized your suggestion made more sense.

Thanks for contributing!
